# syntax=docker.io/docker/dockerfile:1

FROM node:24-alpine

RUN apk add --no-cache \
    git \
    bash \
    curl \
    vim \
    nano \
    htop \
    procps \
    && rm -rf /var/cache/apk/*

WORKDIR /app

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

COPY package*.json ./
COPY .npmrc* ./

RUN npm ci

COPY . .

RUN chown -R nextjs:nodejs /app

USER nextjs

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
ENV TZ=Europe/Berlin
ENV HOSTNAME="0.0.0.0"
ENV PORT=3000
ENV DATA_FILE=/app/public

EXPOSE 3000

CMD ["npm", "run", "dev"]